In [2]:
import sys
print(sys.executable)


/Users/rahmanr12/Desktop/Education/Grad/ML-691/HW-1/Project/venv/bin/python


In [3]:
# !pip3 install numpy

You should consider upgrading via the '/Users/rahmanr12/Desktop/Education/Grad/ML-691/HW-1/Project/venv/bin/python3 -m pip install --upgrade pip' command.


In [6]:
import numpy as np


In [13]:
np.random.seed(42)

x = np.random.randn()
x

0.4967141530112327

In [14]:
# Define ranges for w1 and w2
w1min, w1max = -2.0, 2.0
w2min, w2max = -2.0, 2.0

w1_range = np.arange(w1min,w1max, 0.01)
w2_range = np.arange(w2min,w2max, 0.01)

In [16]:
w1_range.shape

(400,)

In [17]:
W1, W2 = np.meshgrid(w1_range, w2_range)


In [19]:
W1

array([[-2.  , -1.99, -1.98, ...,  1.97,  1.98,  1.99],
       [-2.  , -1.99, -1.98, ...,  1.97,  1.98,  1.99],
       [-2.  , -1.99, -1.98, ...,  1.97,  1.98,  1.99],
       ...,
       [-2.  , -1.99, -1.98, ...,  1.97,  1.98,  1.99],
       [-2.  , -1.99, -1.98, ...,  1.97,  1.98,  1.99],
       [-2.  , -1.99, -1.98, ...,  1.97,  1.98,  1.99]])

In [20]:
W1.shape

(400, 400)

In [23]:
 # Create a stacked array of weight vectors from the meshgrid
W = np.stack([W1.ravel(), W2.ravel()], axis=1)

In [24]:
for idx, (w1, w2) in enumerate(W):
    w = np.array([[w1], [w2]])
    print(w)

    break


[[-2.]
 [-2.]]


In [28]:
 # Create a stacked array of weight vectors from the meshgrid
W_new = np.stack([W1.reshape(-1), W2.reshape(-1)], axis=1)

In [34]:
for idx in range(len(W)):
    w11 = W[idx]
    w22 = W_new[idx]

    if w11[0]!=w22[0] and w11[1]!=w22[1]:
        print(w11,w22)



In [33]:
a = np.array([[1,2,3],[4,5,6]])

print(a.ravel())
print(a.reshape(-1))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
